spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/employee?useSSL=true&useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: xx1314520
  thymeleaf:
    cache: false
  messages:
    basename: i18n.login

mybatis:
  type-aliases-package: com.xinxin.Myspring.pojo
  mapper-locations: classpath:com.xinxin.Myspring.mapper/*Mapper.xml
  configuration:
    #开启mybatis驼峰式命名规则自动转换
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl